### ISSUE TITLE
Rethink of Reset

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_protocol#37]
### Is your feature request related to a problem? Please describe.

Resets as currently implemented cause serious problems, many of which are currently impossible to resolve.

### Describe the solution you'd like

* A complete analysis of the human scenarios which we've hand-waved as 'reset' to date
* For each scenario, identify the outcomes which the humans need (the humans being owner of the initiating atSign / owners of other atSigns which have interacted with the initiating atSign)
* Identify the involvement (of the registrar, atDirectory, atServers, atClients and other, possibly new, actors and software) in achieving those outcomes
* Identify what changes (to the registrar, the atDirecrory, the atProtocol, the atServers, the atClients, and other software) are required to deliver those outcomes

**Comment by xavierchanth** [comment]
https://github.com/atsign-foundation/at_client_sdk/issues/900

**Comment by VJag** [comment]
Analysis of moving from free to a paid atSign is captured here:
https://docs.google.com/document/d/1MOyv_UaxmVFL4sjQ4yMocXXWpH8NSMEHUDMKzT7pL_0/edit?usp=sharing

**Comment by VJag** [comment]
This ticket will be my primary focus in PR56

**Comment by ksanty** [comment]
@gkc can this be closed or @VJag ?

**Comment by VJag** [comment]
Under this ticket, we have analyzed:

1. Reasons for reset (bad data, apps being stuck etc..)
2. Actions that can help unblock a user so that we can prevent a reset (Ability to mark bad data and prompt the user to delete - Data browser app)
3. Easiest path to migrate from free to paid atSign

There are other efforts to reset covered in other tickets. I reckon we can close this ticket.

@gkc @ksanty Please let me know your thoughts.
